# Build Full-Stack Application Workflow
# Web Development Masters Module - Complete App Development

name: build-full-stack-app
description: "End-to-end full-stack application development guide. From database schema to deployed production app with military precision."
author: "Sergeant Doakes & Squad"

config_source: "{project-root}/.bmad/web-dev-masters/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
primary_stack: "{config_source}:primary_stack"
deployment_target: "{config_source}:deployment_target"
output_folder: "{config_source}:output_folder"
date: system-generated

installed_path: "{project-root}/.bmad/custom/modules/web-dev-masters/workflows/build-full-stack-app"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
default_output_file: "{output_folder}/full-stack-build-{{app_name}}-{{date}}.md"

standalone: true
