fragment PageParts on Page {
  __typename
  title
  description
  blocks {
    __typename
    ... on PageBlocksHero {
      heading
      subheading
      backgroundImage
      videoSrc
      ctaText
      ctaLink
      theme
      size
      glassEffect
    }
    ... on PageBlocksFeaturesGrid {
      heading
      columns
      items {
        __typename
        title
        description
        image
        link
      }
    }
    ... on PageBlocksEditorialText {
      heading
      layout
      contentLeft
      contentRight
      backgroundColor
    }
    ... on PageBlocksImageSection {
      image
      videoSrc
      heading
      text
      ctaText
      ctaLink
      overlayPosition
      theme
    }
    ... on PageBlocksCta {
      heading
      subheading
      buttonText
      buttonLink
      theme
    }
    ... on PageBlocksStats {
      heading
      items {
        __typename
        value
        label
      }
      backgroundColor
    }
    ... on PageBlocksTestimonial {
      quote
      author
      role
      authorImage
      backgroundColor
    }
  }
  hero {
    __typename
    heading
    subheading
    image
  }
  seo {
    __typename
    title
    description
    ogImage
  }
  body
}

fragment SettingsParts on Settings {
  __typename
  siteName
  siteDescription
  logo
  navigation {
    __typename
    label
    href
  }
  footer {
    __typename
    copyright
    socialLinks {
      __typename
      platform
      url
    }
  }
}
