# Project Setup Workflow - Tactical Mission Planning
# Web Development Masters Module - Sergeant Doakes Commanding

name: project-setup
description: "Complete project planning and architecture session with military precision. From mission briefing to deployment strategy."
author: "Sergeant Doakes"

# Load module configuration
config_source: "{project-root}/.bmad/web-dev-masters/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
primary_stack: "{config_source}:primary_stack"
deployment_target: "{config_source}:deployment_target"
output_folder: "{config_source}:output_folder"
date: system-generated

# Workflow components
installed_path: "{project-root}/.bmad/custom/modules/web-dev-masters/workflows/project-setup"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{output_folder}/project-brief-{{project_name}}-{{date}}.md"

standalone: true
