# Deploy to Production Workflow
name: deploy-to-production
description: "Production deployment with zero-downtime, monitoring, and rollback capability"
author: "Colonel Forge"
config_source: "{project-root}/.bmad/web-dev-masters/config.yaml"
user_name: "{config_source}:user_name"
deployment_target: "{config_source}:deployment_target"
output_folder: "{config_source}:output_folder"
date: system-generated
installed_path: "{project-root}/.bmad/custom/modules/web-dev-masters/workflows/deploy-to-production"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
default_output_file: "{output_folder}/deployment-{{app_name}}-{{date}}.md"
standalone: true
